// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb7PnAeQfj6VAm8OFB3swjoMJh7ooPD-0',
    appId: '1:529507309746:web:b150bea067ec4b4b08d1ab',
    messagingSenderId: '529507309746',
    projectId: 'spotify-a7fec',
    authDomain: 'spotify-a7fec.firebaseapp.com',
    storageBucket: 'spotify-a7fec.appspot.com',
    measurementId: 'G-YXX8PZZ69T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAG2XPjOyb1OWj86lvL0JMMi-58FW-guY',
    appId: '1:529507309746:android:92e77e770d5727f208d1ab',
    messagingSenderId: '529507309746',
    projectId: 'spotify-a7fec',
    storageBucket: 'spotify-a7fec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT3cq75Mkh0fP5H-OMWHoyer1Jx6S70Uk',
    appId: '1:529507309746:ios:fd1096c93712ae7e08d1ab',
    messagingSenderId: '529507309746',
    projectId: 'spotify-a7fec',
    storageBucket: 'spotify-a7fec.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT3cq75Mkh0fP5H-OMWHoyer1Jx6S70Uk',
    appId: '1:529507309746:ios:fd1096c93712ae7e08d1ab',
    messagingSenderId: '529507309746',
    projectId: 'spotify-a7fec',
    storageBucket: 'spotify-a7fec.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBb7PnAeQfj6VAm8OFB3swjoMJh7ooPD-0',
    appId: '1:529507309746:web:a3de613dfb1ebb6608d1ab',
    messagingSenderId: '529507309746',
    projectId: 'spotify-a7fec',
    authDomain: 'spotify-a7fec.firebaseapp.com',
    storageBucket: 'spotify-a7fec.appspot.com',
    measurementId: 'G-XQQLPKWE70',
  );
}
