// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATxMPsKShmJrviAqm2R8URsaEFwt0wGr4',
    appId: '1:554678138045:web:8c9be1c2b7cfb92d15b3d4',
    messagingSenderId: '554678138045',
    projectId: 'tune-firebase-backend',
    authDomain: 'tune-firebase-backend.firebaseapp.com',
    storageBucket: 'tune-firebase-backend.appspot.com',
    measurementId: 'G-9GJ81S6DE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATq_IgJqXi_zTLhtEDE2eWTj4ZnK-SkoM',
    appId: '1:554678138045:android:0c690d721cc4f20115b3d4',
    messagingSenderId: '554678138045',
    projectId: 'tune-firebase-backend',
    storageBucket: 'tune-firebase-backend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNkeP2q9eibh8zil2PEyfeXmbL874e-B0',
    appId: '1:554678138045:ios:adb2c7b9125a5c2215b3d4',
    messagingSenderId: '554678138045',
    projectId: 'tune-firebase-backend',
    storageBucket: 'tune-firebase-backend.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNkeP2q9eibh8zil2PEyfeXmbL874e-B0',
    appId: '1:554678138045:ios:adb2c7b9125a5c2215b3d4',
    messagingSenderId: '554678138045',
    projectId: 'tune-firebase-backend',
    storageBucket: 'tune-firebase-backend.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATxMPsKShmJrviAqm2R8URsaEFwt0wGr4',
    appId: '1:554678138045:web:c5479b79c47b97d215b3d4',
    messagingSenderId: '554678138045',
    projectId: 'tune-firebase-backend',
    authDomain: 'tune-firebase-backend.firebaseapp.com',
    storageBucket: 'tune-firebase-backend.appspot.com',
    measurementId: 'G-7X0ZZ90CKJ',
  );
}
